# Generated by Django 5.2.10 on 2026-06-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='otb_value',
        ),
    ]
