# Generated by Django 5.2.10 on 2026-06-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0002_remove_subcategory_otb_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='unit_price',
        ),
    ]
