# Generated by Django 5.2.10 on 2026-06-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0004_remove_subcategory_otb_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbudget',
            name='vendor',
        ),
        migrations.AddField(
            model_name='adminbudget',
            name='subcategory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='po_sheet.subcategory'),
            preserve_default=False,
        ),
    ]
