# Generated by Django 5.2.10 on 2026-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0005_remove_adminbudget_vendor_adminbudget_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='po_sheet.category')),
            ],
            options={
                'verbose_name': 'Category Size',
                'verbose_name_plural': 'Category Sizes',
                'unique_together': {('category', 'name')},
            },
        ),
    ]
