# Generated by Django 5.2.10 on 2026-06-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0006_categorysize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='po_sheet.subcategory')),
            ],
            options={
                'verbose_name': 'Sub-Category Size',
                'verbose_name_plural': 'Sub-Category Sizes',
                'unique_together': {('subcategory', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='CategorySize',
        ),
    ]
