# Generated by Django 5.2.10 on 2026-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0008_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
