# Generated by Django 5.2.10 on 2026-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0009_remove_purchaseorder_status_purchaseorder_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='size_allocations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
