# Generated by Django 5.2.10 on 2026-06-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0010_purchaseorderitem_size_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
