# Generated by Django 5.2.10 on 2026-06-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0011_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='pcs_loose',
        ),
    ]
