# Generated by Django 5.2.10 on 2026-06-25 13:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0013_production_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='po_sheet.buyer'),
        ),
        migrations.AlterField(
            model_name='adminbudget',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Stock', 'Stock'), ('Promo', 'Promo'), ('Sample', 'Sample')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item_type',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Stock', 'Stock'), ('Promo', 'Promo'), ('Sample', 'Sample')], default='Fresh', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
