# Generated by Django 5.2.10 on 2026-06-26 05:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0014_alter_subcategory_unique_together_subcategory_buyers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_from_range', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_to_range', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buying_from_range', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('buying_to_range', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='po_sheet.subcategory')),
            ],
            options={
                'verbose_name': 'SubCategory Price Range',
                'verbose_name_plural': 'SubCategory Price Ranges',
                'unique_together': {('subcategory', 'sales_from_range', 'sales_to_range')},
            },
        ),
    ]
