# Generated by Django 5.2.10 on 2026-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0015_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbudget',
            name='approved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
