# Generated by Django 5.2.10 on 2026-06-26 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0019_remove_adminbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='season',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['buyer', 'is_draft'], name='po_buyer_draft_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['season', 'is_draft'], name='po_season_draft_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'subcategory'], name='poi_po_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city'], name='vendor_city_idx'),
        ),
    ]
