# Generated by Django 5.2.10 on 2026-07-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0021_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategorypricerange',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategorypricerange',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='po_sheet.season'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategorypricerange',
            unique_together={('subcategory', 'season', 'sales_from_range', 'sales_to_range')},
        ),
    ]
