# Generated by Django 5.2.10 on 2026-07-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0022_alter_subcategorypricerange_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='po_sheet.subcategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='po_sheet.vendor')),
            ],
            options={
                'verbose_name': 'Sub-Category Ratio',
                'verbose_name_plural': 'Sub-Category Ratios',
                'unique_together': {('vendor', 'subcategory')},
            },
        ),
    ]
