# Generated by Django 5.2.10 on 2026-07-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0023_subcategoryratio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoryratio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategoryratio',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='po_sheet.buyer'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryratio',
            unique_together={('vendor', 'buyer', 'subcategory')},
        ),
    ]
