# Generated by Django 5.2.10 on 2026-07-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0024_alter_subcategoryratio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ratio Type',
                'verbose_name_plural': 'Ratio Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryratio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategoryratio',
            name='ratio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='po_sheet.ratiotype'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryratio',
            unique_together={('vendor', 'buyer', 'subcategory', 'ratio_type')},
        ),
    ]
