# Generated by Django 5.2.10 on 2026-07-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_sheet', '0025_ratiotype_alter_subcategoryratio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ratio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po_sheet.ratiotype'),
        ),
    ]
